service: auction-service

plugins:
  # - serverless-bundle
  # - serverless-pseudo-parameters
  - serverless-offline

provider:
  name: aws
  runtime: nodejs16.x
  memorySize: 256
  stage: ${opt:stage, 'dev'}
  region: ap-south-1

resources:
  Resources:
    AuctionsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: AuctionsTable
        BillingMode: PAY_PER_REQUEST
        AttributesDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH 
  
functions:
  createAuction:
    handler: src/handlers/createAuction.handler
    events:
      - http:
          method: GET
          path: /auction
      
custom:
  bundle:
    linting: false
