service: auction-service

plugins:
  # - serverless-bundle
  # - serverless-pseudo-parameters
  - serverless-offline

provider:
  name: aws
  runtime: nodejs16.x
  memorySize: 256
  stage: ${opt:stage, 'dev'}
  region: ap-south-1
  environment:
    AUCTION_TABLE_NAME: {Ref: AuctionsTable}
  iamRoleStatements:
    - ${file(iam/AuctionTableIAM.yml):AuctionsTableIAM}

resources:
  Resources:
    AuctionsTable: ${file(resources/AuctionTable.yml):AuctionsTable}
functions:
  createAuction:
    handler: src/handlers/createAuction.handler
    events:
      - http:
          method: POST
          path: /auction
      
custom:
 
  # AuctionsTable:
  #   name: !Ref AuctionsTable
  #   arn:  !GetAtt AuctionsTable.Arn
  # bundle:
  #   linting: false
